---
- name: Installing andrewrothstein.openssl
  ansible.builtin.include_role:
    name: andrewrothstein.openssl
  vars:
    openssl_include_dev_pkgs: true
- name: Installing andrewrothstein.curl
  ansible.builtin.include_role:
    name: andrewrothstein.curl
- name: Installing andrewrothstein.epel
  ansible.builtin.include_role:
    name: andrewrothstein.epel
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Install dep pkgs
  become: true
  become_user: root
  ansible.builtin.package:
    name: '{{ dotnet_deps }}'
    state: present
