---
- include_role:
    name: andrewrothstein.openssl
  vars:
    openssl_include_dev_pkgs: true
- include_role:
    name: andrewrothstein.curl
- include_role:
    name: andrewrothstein.epel
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: install dep pkgs
  become: true
  become_user: root
  package:
    name: '{{ dotnet_deps }}'
    state: present
